/**
 * PERMISSION DICTIONARY (NORMALIZED)
 * Single Source of Truth. No duplicates.
 */

// 1. CAPABILITIES (Permissions checked in UI/Hooks)
export const PERM_CAPABILITIES = {
  MANAGE_TOURNAMENT: 'CAP_MANAGE_TOURNAMENT', 
  VIEW_HIDDEN_DATA: 'CAP_VIEW_HIDDEN',        
  MANAGE_MATCH: 'CAP_MANAGE_MATCH',           
  OVERRIDE_MATCH: 'CAP_OVERRIDE_MATCH',       
  ACT_AS_CAPTAIN: 'CAP_ACT_AS_CAPTAIN',       
  REPORT_SCORE: 'CAP_REPORT_SCORE',
  EDIT_ROSTER: 'CAP_EDIT_ROSTER'              
};

// 2. OPERATIONS (Action types for Audit Logs)
export const PERM_OPERATIONS = {
  SYNC_ROSTER: 'OP_SYNC_ROSTER',
  GENERATE_BRACKET: 'OP_GENERATE_BRACKET',
  FORCE_WIN: 'OP_FORCE_WIN',
  UPDATE_SCORE: 'OP_UPDATE_SCORE',
  SUBMIT_VETO: 'OP_SUBMIT_VETO',
  FILE_DISPUTE: 'OP_FILE_DISPUTE'
};
