export const PERM_ACTIONS = {
  SYNC_ROSTER: 'SYNC_ROSTER',
  GENERATE_BRACKET: 'GENERATE_BRACKET',
  RESET_TOURNAMENT: 'RESET_TOURNAMENT',
  CAN_MANAGE_MATCH: 'UPDATE_MATCH',
  CAN_MANAGE_BRACKET: 'GENERATE_BRACKET',
  UPDATE_MATCH: 'UPDATE_MATCH',
  SWAP_TEAMS: 'SWAP_TEAMS',
  CHANGE_CONFIG: 'CHANGE_CONFIG',
  EDIT_PLAYER: 'EDIT_PLAYER',
  VIEW_LOGS: 'VIEW_LOGS',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  VETO_ACT: 'VETO_ACT',
  VIEW_SERVER_IP: 'VIEW_SERVER_IP',
  VETO_OVERRIDE: 'VETO_OVERRIDE',
  VIEW_SENSITIVE: 'VIEW_SENSITIVE'
};
