/**
 * ⚖️ PERMISSION MATRIX
 * Defines the Laws of Physics for the platform.
 */

import { ROLES } from './definitions';

// 1. ATOMIC CAPABILITIES
export const PERMISSIONS = {
  // 🛰️ SYSTEM
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_HIDDEN_DATA: 'view_hidden_data', // IP/Passwords
  MANAGE_TOURNAMENT: 'manage_tournament',
  MANAGE_MATCH: 'manage_match',
  OVERRIDE_MATCH: 'override_match',
  
  // 🎥 MEDIA
  UPLOAD_MEDIA: 'upload_media',
  MANAGE_ASSETS: 'manage_assets', // Team Logos/Audio
  BROADCAST_FEED: 'broadcast_feed',
  
  // 🎮 COMPETITION
  ACT_AS_CAPTAIN: 'act_as_captain',
  EDIT_ROSTER: 'edit_roster',
  VIEW_PRO_STATS: 'view_pro_stats'
};

// 2. INHERITANCE BLOCKS
const BLOCK_PLAYER = [PERMISSIONS.UPLOAD_MEDIA, PERMISSIONS.VIEW_PRO_STATS];
const BLOCK_TEAM   = [...BLOCK_PLAYER, PERMISSIONS.ACT_AS_CAPTAIN, PERMISSIONS.EDIT_ROSTER];
const BLOCK_STAFF  = [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_HIDDEN_DATA];

// 3. ASSIGNMENT MATRIX
export const ROLE_CAPABILITIES = {
  [ROLES.OWNER]:     Object.values(PERMISSIONS), // God Mode
  [ROLES.ADMIN]:     [...BLOCK_STAFF, PERMISSIONS.MANAGE_TOURNAMENT, PERMISSIONS.MANAGE_MATCH, PERMISSIONS.OVERRIDE_MATCH, PERMISSIONS.MANAGE_ASSETS],
  [ROLES.ORGANIZER]: [...BLOCK_STAFF, PERMISSIONS.MANAGE_TOURNAMENT],
  [ROLES.CASTER]:    [...BLOCK_STAFF, PERMISSIONS.MANAGE_MATCH, PERMISSIONS.BROADCAST_FEED],
  [ROLES.CREW]:      [...BLOCK_STAFF, PERMISSIONS.MANAGE_MATCH],
  [ROLES.CAPTAIN]:   BLOCK_TEAM,
  [ROLES.PLAYER]:    BLOCK_PLAYER,
  [ROLES.GUEST]:     []
};
